---
# tasks file for apigee-opdk-devportal-config
- name: Determine interface name
  include_tasks: interface.yml

- name: Regional Management Server IP Address
  include_tasks: local_mgmt_ip.yml

- name: Configure postgres
  import_tasks: postgres.yml

- name: Assert that Devportal attributes are available
  assert:
    that:
      - dp_pg_name is defined
      - dp_pg_user is defined
      - dp_pg_pass is defined
      - dp_pg_host is defined
      - dp_pg_database is defined
      - dp_drupal_pg_user is defined
      - dp_drupal_pg_pass is defined
      - dp_admin_firstname is defined
      - dp_admin_lastname is defined
      - dp_admin_pwd is defined
      - dp_admin_email is defined
      - org_name is defined
      - local_mgmt_ip is defined
      - dp_devadmin_user is defined
      - dp_devadmin_pwd is defined
      - dp_php_fpm_port is defined
      - opdk_smtp_host is defined
      - opdk_smtp_ssl is defined
      - opdk_smtp_port is defined
      - opdk_smtp_user is defined
      - opdk_smtp_password is defined
      - ms_port is defined

- name: Remove pre-exisiting PHP packages
  tags: ['os', 'php']
  ignore_errors: yes
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ php_packages }}"

- name: Drupal Admin and Postgres admin cannot be the same username
  fail:
    msg: "Drupal admin and postgres admin cannot be the same user"
  when: (dp_drupal_pg_user == pg_user) or (dp_drupal_pg_user == dp_devadmin_user)

- name: Remove the old dev portal db response file
  become: yes
  file:
    path: "{{ opdk_portal_config_file }}"
    state: absent
  when: manual_devportal_response_file is not defined or not manual_devportal_response_file

- name: Ensure that a folder exists for the file to be generated
  become: yes
  file:
    path: "{{ opdk_portal_config_file | dirname }}"
    state: directory

- name: Construct the dev portal silent-install file
  become: yes
  template:
    src: 'devportal-silent-install.conf.j2'
    dest: "{{ opdk_portal_config_file }}"
    force: yes
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0655
  when: manual_devportal_response_file is not defined or not manual_devportal_response_file

- name: Copy provided silent-install file
  become: yes
  copy:
    src: "{{ manual_devportal_response_file }}"
    dest: "{{ opdk_portal_config_file }}"
    owner: '{{ opdk_user_name }}'
    group: '{{ opdk_group_name }}'
    mode: 0655
  when: manual_devportal_response_file is defined and manual_devportal_response_file
