---
# tasks file for apigee-opdk-setup-os
- name: Update basic yum os packages
  import_role:
    name: apigee-opdk-yum-packages
  vars:
    yum_os_minimum_packages: "{{ yum_packages }}"

- name: Comment out IPv6 localhost entry
  become: yes
  tags: ['ipv6']
  replace:
    dest: /etc/hosts
    regexp: "{{ item.regexp }}"
    replace: '{{ item.replace }}'
  with_items: "{{ clear_etc_hosts }}"

- block:
  - name: Start rngd service
    service:
      name: rngd
      enabled: yes
      state: started

  - name: Ensure rngd config directory is in place
    file:
      path: /usr/lib/systemd/system
      state: directory

  - name: Ensure rngd config file is in place
    file:
      path: /usr/lib/systemd/system/rngd.service
      state: touch

  - name: Patch rngd service unit
    replace:
      dest: /usr/lib/systemd/system/rngd.service
      regexp: ^(ExecStart=/sbin/rngd -f)$
      replace: \1 -r /dev/urandom
    register: rngd_unit

  - name: Reload systemd
    command: systemctl daemon-reload
    when: rngd_unit.changed

  - name: Restart and enable rngd
    service:
      name: rngd
      state: restarted
      enabled: yes
    when: rngd_unit.changed

  - name: Start and enable rngd
    service:
      name: rngd
      state: started
      enabled: yes
    when: not rngd_unit.changed
  become: yes
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version_compare("6", ">")

- name: Update for apigee installation environment
  become: yes
  lineinfile:
    dest: /etc/environment
    regexp: "^export CONTINUE_ON_WARNING="
    line: 'export CONTINUE_ON_WARNING={{ apigee_continue_on_warning }}'
    backup: yes
