---
# tasks file for apigee-opdk-server-registration-state

- name: Obtain server registration report
  opdk_server_registration_state:
    server_self: '{{ server_self }}'
    username: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'
    mgmt_server_ip: '{{ local_mgmt_ip }}'

#- name: Construct self report variable name
#  set_fact:
#    self_report_name: 'edge_{{ server_type }}_self'

- name: Server self report
  debug:
    msg: "{{ hostvars[inventory_hostname]['registered'] }}"

