---
# tasks file for apigee-opdk-start-components
- block:
  - name: Stop all Apigee components on the node
    ignore_errors: yes
    shell: '/opt/apigee/apigee-service/bin/apigee-all stop'
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
      UP_TIMEOUT: '{{ up_timeout | default(60) }}'
    when: opdk_version is version_compare('4.16.01', '>=') and opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

  - name: DEBUG_MODE - Stop all Apigee components on the node
    ignore_errors: yes
    shell: 'bash -x /opt/apigee/apigee-service/bin/apigee-all stop'
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
      UP_TIMEOUT: '{{ up_timeout | default(60) }}'
    when: opdk_version is version_compare('4.16.01', '>=') and opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

  when: component_name == 'all'

- block:
  - name: Stop a specific Apigee component on the node
    ignore_errors: yes
    shell: '/opt/apigee/apigee-service/bin/apigee-service {{ component_name }} stop'
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
      UP_TIMEOUT: '{{ up_timeout | default(60) }}'
    when: opdk_version is version_compare('4.16.01', '>=') and opdk_debug_mode is not defined or opdk_debug_mode | trim | lower == 'off'

  - name: DEBUG_MODE - Stop a specific Apigee component on the node
    ignore_errors: yes
    shell: 'bash -x /opt/apigee/apigee-service/bin/apigee-service {{ component_name }} stop'
    environment:
      http_proxy: "{{ http_proxy | default('') }}"
      https_proxy: "{{ https_proxy | default('') }}"
      no_proxy: "{{ no_proxy | default('') }}"
      PORT_TIMEOUT: '{{ port_timeout | default(60) }}'
      UP_TIMEOUT: '{{ up_timeout | default(60) }}'
    when: opdk_version is version_compare('4.16.01', '>=') and opdk_debug_mode is defined and opdk_debug_mode | trim | lower == 'on'

  when: component_name != 'all'
