---
# defaults file for apigee-opdk-setup-ansible

# Default local Apigee Workspace
local_workspace: "~/apigee-workspace"

# Default Ansible workspace, used if not provided.
ansible_config_folder: "{{ local_workspace }}/ansible"

# Set Ansible workspace to either provided or default
target_ansible_workspace: "{{ ansible_workspace | default(ansible_config_folder) }}"

library_folder: "{{ target_ansible_workspace }}/library"

target_ansible_configurations: "{{ target_ansible_workspace }}/multi-planet-configurations"

target_apigee_workspace: "{{ apigee_workspace | default(local_workspace) }}"

default_ansible_config: "~/.ansible.cfg"

target_apigee_secure_folder: "{{ apigee_secure_folder | default(target_apigee_workspace) }}"

target_apigee_custom_properties_folder: "{{ apigee_custom_properties_folder | default(target_apigee_workspace) }}"

starter_templates:
- { dest_path: "{{ target_apigee_secure_folder }}", file_name: credentials.yml }
- { dest_path: "{{ target_apigee_custom_properties_folder }}", file_name: custom-properties.yml }

setup_dirs:
- "{{ target_ansible_configurations }}"
- "{{ target_ansible_workspace }}/roles"
- "{{ target_ansible_workspace }}/logs"
- "{{ target_ansible_workspace }}/tmp"
- "{{ target_ansible_workspace }}/inventory"
- "{{ ansible_workspace }}"
- "{{ target_apigee_secure_folder }}"
- "{{ target_apigee_custom_properties_folder }}"

#pip_config:
#- { dest_path: "{{ target_apigee_workspace }}/apigee", file_name: pip.conf }

private_key_file: ~/.ssh/id_rsa

repository_secure_endpoint_https: "https://github.com/carlosfrias"

repository_secure_endpoint_ssh: "git@github.com:carlosfrias"

checkout_type: https

template_repos:
- { dir: '{{ target_ansible_configurations }}', repo_name: apigee-opdk-ansible-configuration-samples, dest_name: templates }
- { dir: "{{ target_ansible_workspace }}/inventory", repo_name: apigee-opdk-ansible-inventory-samples, dest_name: templates }

os_packages:
- git
- rsync
- tree
- ansible
