---
# tasks file for apigee-opdk-extension-ds
- name: Assert that required attributes are available
  assert:
    that:
    - nodetool is defined
    - java_home is defined
    - private_address is defined
    - region is defined
    msg: "Please provide the missing attribute."

- name: Nodetool flush before repair
  shell: '{{ nodetool }} flush'
  args:
    removes: "{{ nodetool }}"
  environment:
    JAVA_HOME: '{{ java_home }}'

- name: Rebuild Cassandra nodes
  shell: '{{ nodetool }} -h {{ private_address }} rebuild {{ region }}'
  args:
    removes: "{{ nodetool }}"
  environment:
    JAVA_HOME: '{{ java_home }}'

- name: Nodetool flush after rebuild
  shell: '{{ nodetool }} cleanup'
  args:
    removes: "{{ nodetool }}"
  environment:
    JAVA_HOME: '{{ java_home }}'

