---
# tasks file for apigee-opdk-settings-cassandra/
- name: Fail if ds group is not provided
  fail:
    msg: 'ds group is not defined in the inventory file, please define the ds group in the inventory file'
  when: groups['ds'] is not defined

- name: Fail if dc-1 group is not provided
  fail:
    msg: 'dc-1 group is not defined in the inventory file, please define the dc-1 group in the inventory file'
  when: groups['dc-1'] is not defined

- name: Fail if dc-1-ds group is not provided
  fail:
    msg: 'dc-1-ds group is not defined in the inventory file, please define the dc-1-ds group in the inventory file'
  when: groups['dc-1-ds'] is not defined

- name: Fail if dc-1-ms group is not provided
  fail:
    msg: 'dc-1-ms group is not defined in the inventory file, please define the dc-1-ms group in the inventory file'
  when: groups['dc-1-ms'] is not defined

- name: Assert variables are available
  assert:
    that:
    - private_address is defined
    - region is defined
    msg: "Please provide the missing variable"

- name: Construct cassandra hosts configuration
  become: yes
  cassandra_hosts:
    inventory_hostname: '{{ inventory_hostname }}'
    hostvars: '{{ hostvars }}'
  when: manual_response_file is not defined or not manual_response_file
