---
# tasks file for apigee-opdk-setup-scopes-add

- name: Determine interface name
  include_tasks: interface.yml

- name: Regional Management Server IP Address
  include_tasks: local_mgmt_ip.yml

- name: Assert that attributes are available.
  assert:
    that:
      - "org_name is defined and org_name | trim | length > 0"
      - "env_name is defined and env_name | trim | length > 0"
      - "local_mgmt_ip is defined and local_mgmt_ip | trim | length > 0"
      - "opdk_user_email is defined and opdk_user_email | trim | length > 0"
      - "opdk_user_pass is defined and opdk_user_pass | trim | length > 0"
    msg: "Please provide the missing attribute"

- name: Add scope to analytics group
  uri:
    user: '{{ opdk_user_email }}'
    password: '{{ opdk_user_pass }}'
    method: POST
    body_format: json
    url: http://{{ local_mgmt_ip }}:8080/v1/analytics/groups/ax/{{ ax_group }}/scopes?org={{ org_name }}&env={{ env_name }}
  environment:
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"
    no_proxy: "{{ no_proxy | default('') }}"



