---
# tasks file for fetch-found-files
- name: Validate that we have download_pattern
  fail:
    msg: "Please provide a download_pattern list that follows dir: 'directory name', pattern: 'file pattern'"
  when: download_pattern is not defined

- name: Create download folder
  become: no
  file:
    path: "{{ download_folder }}"
    state: directory
  delegate_to: 127.0.0.1

- name: Determine that download folder exists
  stat:
    path: "{{ download_folder }}"
  delegate_to: 127.0.0.1
  register: folder_state

- name: Assert the state of the download folder
  assert:
    that:
    - folder_state.stat.exists == true
    msg: "Download folder to store fetched files does not exists, please create the folder: {{ download_folder }}"

- name: Find download log files
  find:
    path: '{{ item.dir }}'
    pattern: '{{ item.pattern }}'
    file_type: file
    hidden: yes
    recurse: yes
  with_items: "{{ download_pattern }}"
  register: downloads

- name: Download files
  fetch:
    src: "{{ item.1.path }}"
    dest: "{{ download_folder }}"
  with_subelements:
  - "{{ downloads.results }}"
  - files
