---
# defaults file for apigee-opdk-yum-repository/
#redhat_repositories:
#- { name: rhel-7-server-extras-rpms,
#    baseurl: "https://luxfavlpa001.verizon.com/pulp/repos/Verizon/1m0w-1w/RHEL7_SOE/content/dist/rhel/server/7/7Server/$basearch/extras/os"
#  }
#- { name: rhel-7-server-optional-rpms,
#    baseurl: "https://luxfavlpa001.verizon.com/pulp/repos/Verizon/1m0w-1w/RHEL7_SOE/content/dist/rhel/server/7/7Server/$basearch/optional/os"
#  }
#- { name: rhel-7-server-rpms,
#    baseurl: "https://luxfavlpa001.verizon.com/pulp/repos/Verizon/1m0w-1w/RHEL7_SOE/content/dist/rhel/server/7/7Server/$basearch/os"
#  }
#- { name: rhel-7-server-satellite-tools-6.2-rpms,
#    baseurl: "https://luxfavlpa001.verizon.com/pulp/repos/Verizon/1m0w-1w/RHEL7_SOE/content/dist/rhel/server/7/7Server/$basearch/rhscl/1/os"
#  }
#- { name: rhel-server-rhscl-7-rpms,
#    baseurl: "https://luxfavlpa001.verizon.com/pulp/repos/Verizon/1m0w-1w/RHEL7_SOE/content/dist/rhel/server/7/7Server/$basearch/rhscl/1/os"
#  }
#- { name: rhel-7-server-rhn-tools-rpms,
#    baseurl: "https://luxfavlpa001.verizon.com/pulp/repos/Verizon/1m0w-1w/RHEL7_SOE/content/dist/rhel/server/7/7Server/$basearch/rhn-tools/os"
#  }
#- { name: rhel-7-server-thirdparty-oracle-java-rpms,
#    baseurl: " https://luxfavlpa001.verizon.com/pulp/repos/Verizon/1m0w-1w/RHEL7_SOE/content/dist/rhel/server/7/7Server/$basearch/oracle-java/os"
#  }


yum_repositories_enabled: true

#yum_repositories:
#- { name: "Red Hat Enterprise Linux 7 Server (RPMs)",
#    baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-rpms/Packages",
#    repo_id: "rhel-7-server-rpms",
#    yum_repo_filename: "{{ yum_repo_filename }}",
#    gpgcheck: 'no'}
#- { name: "Red Hat Software Collections RPMs for Red Hat Enterprise Linux 7 Server",
#    baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-server-rhscl-7-rpms/Packages",
#    repo_id: "rhel-server-rhscl-7-rpms",
#    yum_repo_filename: "{{ yum_repo_filename }}",
#    gpgcheck: 'no'}
#- { name: "Red Hat Satellite Tools 6.2 (for RHEL 7 Server) (RPMs)",
#    baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-satellite-tools-6.2-rpms/Packages",
#    repo_id: "rhel-7-server-satellite-tools-6.2-rpms",
#    yum_repo_filename: "{{ yum_repo_filename }}",
#    gpgcheck: 'no'}
#- { name: "Red Hat Enterprise Linux 7 Server - Supplementary (RPMs)",
#    baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-supplementary-rpms/Packages",
#    repo_id: "rhel-7-server-supplementary-rpms",
#    yum_repo_filename: "{{ yum_repo_filename }}",
#    gpgcheck: 'no'}
#- { name: "Red Hat Enterprise Linux 7 Server - RH Common (RPMs)",
#    baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-rh-common-rpms/Packages",
#    repo_id: "rhel-7-server-rh-common-rpms",
#    yum_repo_filename: "{{ yum_repo_filename }}",
#    gpgcheck: 'no'}
#- { name: "Red Hat Enterprise Linux 7 Server - Extras (RPMs)",
#    baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-extras-rpms/Packages",
#    repo_id: "rhel-7-server-extras-rpms",
#    yum_repo_filename: "{{ yum_repo_filename }}",
#    gpgcheck: 'no'}
#- { name: "Red Hat Enterprise Linux 7 Server - Optional (RPMs)",
#    baseurl: "http://luxsc1lna001.itcent.ebiz.verizon.com/rhel7/rhel-7-server-optional-rpms/Packages",
#    repo_id: "rhel-7-server-optional-rpms",
#    yum_repo_filename: "{{ yum_repo_filename }}",
#    gpgcheck: 'no'}

