---
- name: Update cache with key and value
  set_fact:
    cacheable: yes
    nodetool: '{{ nodetool }}'
    cqlsh: '{{ cqlsh }}'
    psql: "{{ psql }}"
    apigee_service: '{{ apigee_home }}/apigee-service/bin/apigee-service'
    apigee_setup: '{{ apigee_home }}/apigee-setup/bin/setup.sh'
    apigee_update: '{{ apigee_home }}/apigee-setup/bin/update.sh'
    apigee_all: '{{ apigee_home }}/apigee-service/bin/apigee-all'
    target_response_file_path: '{{ opdk_resources_path }}/edge-response-{{ opdk_version }}-{{ region }}.conf'
    opdk_portal_config_file: '{{ opdk_resources_path }}/edge-devportal-response-{{ opdk_version }}.conf'
    opdk_portal_db_config_file: '{{ opdk_resources_path }}/edge-devportal-postgres-response.conf'
    opdk_resources_path: '{{ opdk_resources_path }}'
    apigee_home: '{{ apigee_home }}'
    opdk_version: '{{ opdk_version }}'
#  - { key: "influx: "{{ apigee_home }}/apigee-influxdb/usr/bin/influx"
    local_apigee_path: "{{ local_apigee_path }}"
    local_apigee_secure: '{{ local_apigee_secure }}'
#    apigee_data_backup_archive_name: '{{ apigee_data_backup_archive_name }}'
#    apigee_archive_storage_folder: '{{ apigee_archive_storage_folder }}'
#    apigee_postgresql_data_dir: "{{ apigee_postgresql_data_dir }}"
#    apigee_validate_config_file: "{{ apigee_validate_config_file }}"
#    opdk_mp_pod: '{{ opdk_mp_pod }}'
#    opdk_ldap_type: '{{ opdk_ldap_type }}
#    use_opdk_ldap_remote_host: '{{ use_opdk_ldap_remote_host }}'
#    opdk_enable_ax: '{{ opdk_enable_ax }}'
#    default_mp_pod: '{{ default_mp_pod }}'
#    opdk_use_zk_cluster: '{{ opdk_use_zk_cluster }}'
#    opdk_cass_clustername: '{{ opdk_cass_clustername }}'
#    opdk_use_cass_cluster: '{{ opdk_use_cass_cluster }}'
#    opdk_smtp_skip: '{{ opdk_smtp_skip }}'
#    opdk_smtp_host: '{{ opdk_smtp_host }}'
#    opdk_smtp_port: '{{ opdk_smtp_port }}'
#    opdk_smtp_ssl: '{{ opdk_smtp_ssl }}'
#    opdk_cass_auth: '{{ opdk_cass_auth }}'
#    consumer_group: '{{ consumer_group }}'
#    ldap_data_port: '{{ ldap_data_port }}'
#    edge_proxy_port: '{{ edge_proxy_port }}'
#    ui_http_port: '{{ ui_http_port }}'
#    pg_ext_mgmt_port: '{{ pg_ext_mgmt_port }}'
#    pg_db_port: '{{ pg_db_port }}'
#    pg_int_mgmt_port: '{{ pg_int_mgmt_port }}'
#    pg_jmx_port: '{{ pg_jmx_port }}'
#    qpid_ext_mgmt_port: '{{ qpid_ext_mgmt_port }}'
#    router_int_mgmt_port: '{{ router_int_mgmt_port }}'
#    qpid_jmx_port: '{{ qpid_jmx_port }}'
#    qpid_int_mgmt_port: '{{ qpid_int_mgmt_port }}'
#    qpid_messaging_port: '{{ qpid_messaging_port }}'
#    router_ext_mgmt_port: '{{ router_ext_mgmt_port }}'
#    router_jmx_port: '{{ router_jmx_port }}'
#    ms_port: '{{ ms_port }}'
#    ms_jmx_port: '{{ ms_jmx_port }}'
#    mp_router_port: '{{ mp_router_port }}'
#    mp_jmx_port: '{{ mp_jmx_port }}'
#    mp_ext_mgmt_port: '{{ mp_ext_mgmt_port }}'
#    mp_int_mgmt_port: '{{ mp_int_mgmt_port }}'
#    zk_voter_port: '{{ zk_voter_port }}'
#    zk_leader_port: '{{ zk_leader_port }}'
#    zk_data_port: '{{ zk_data_port }}'
#    cassandra_ssl_gossip_port: '{{ cassandra_ssl_gossip_port }}'
#    cassandra_non_ssl_gossip_port: '{{ cassandra_non_ssl_gossip_port }}'
#    cassandra_cql_native_port: '{{ cassandra_cql_native_port }}'
#    cassandra_thrift_client_port: '{{ cassandra_thrift_client_port }}'
#    cassandra_jmx_port: '{{ cassandra_jmx_port }}'
#    qpid_ext_mgmt_port: '{{ qpid_ext_mgmt_port }}'
#    ms_port: '{{ ms_port }}'
#    influxdb_port: '{{ influxdb_port }}'
#    influxdb_system_port: '{{ influxdb_system_port }}'
#    env_name: '{{ env_name }}'
#    ax_group: '{{ ax_group }}'
#    virtual_host_name: '{{ virtual_host_name }}'
#    virtual_host_port: '{{ virtual_host_port }}'
#    last_name: '{{ last_name }}'
#    first_name: '{{ first_name }}'
#    new_user: '{{ new_user }}'
#    org_name: '{{ org_name }}'
#    opdk_bind_on_all_interfaces: '{{ opdk_bind_on_all_interfaces }}'
#    opdk_smtp_mail_from: '{{ opdk_smtp_mail_from }}'
#    enable_system_check: '{{ enable_system_check }}'
#    opdk_baas_silent_install_file_path: '{{ opdk_resources_path }}/edge-baas-response.conf'
