---
- name: Normalized name for management server local ip if on dc-1
  set_fact:
    cacheable: yes
    local_mgmt_ip: "{{ hostvars[groups['dc-1-ms'][0]][interface_name].ipv4.address }}"
  when: groups['dc-1'] is defined and groups['dc-1-ms'] is defined and inventory_hostname in groups['dc-1'] and hostvars[groups['dc-1-ms'][0]][interface_name].ipv4.address is defined

- name: Normalized name for management server local ip if on dc-2
  set_fact:
    cacheable: yes
    local_mgmt_ip: "{{ hostvars[groups['dc-2-ms'][0]][interface_name].ipv4.address }}"
  when: groups['dc-2'] is defined and groups['dc-2-ms'] is defined and inventory_hostname in groups['dc-2'] and hostvars[groups['dc-1-ms'][0]][interface_name].ipv4.address is defined

- name: Normalized name for management server local ip to dc-1 if current node is not on dc-1 or dc-2
  set_fact:
    cacheable: yes
    local_mgmt_ip: "{{ hostvars[groups['dc-1-ms'][0]][interface_name].ipv4.address }}"
  when: local_mgmt_ip is not defined or local_mgmt_ip | trim | length == 0
