---
- name: Assert existence of private address
  assert:
    that:
      - "hostvars[inventory_hostname][interface_name].ipv4.address"
    msg: "Unable to retrieve private address"

- name: Normalized name for private address
  set_fact:
    cacheable: yes
    private_address: '{{ hostvars[inventory_hostname][interface_name].ipv4.address }}'

- block:

  - name: Update EC2 for private ip on AWS
    ec2_metadata_facts:
    when: ansible_ec2_local_ipv4 is not defined

  - name: Normalized name for private address on AWS
    set_fact:
      cacheable: yes
      private_address: '{{ ansible_ec2_local_ipv4 }}'
    when: ansible_ec2_local_ipv4 is defined

  when: ansible_bios_version is defined and ansible_bios_version | search('amazon')

