---
- block:

  - name: Setup utilities in cache
    tags: ['cache']
    set_fact:
      cacheable: yes
      nodetool: '{{ apigee_home }}/apigee-cassandra/bin/nodetool'
      cqlsh: '{{ apigee_home }}/apigee-cassandra/bin/cqlsh'
      cassandra_cli: '{{ apigee_home }}/apigee-cassandra/bin/cassandra-cli'

  when: profile is defined and profile == 'ds'

- block:

  - name: Setup utilities in cache
    tags: ['cache']
    set_fact:
      cacheable: yes
      ldapsearch: '/usr/bin/ldapsearch'

  when: profile is defined and profile == 'ms'

- block:

  - name: Setup utilities in cache
    tags: ['cache']
    set_fact:
      cacheable: yes
      psql: '"/usr/bin/psql"'

  when: profile is defined and profile == 'ps'

- block:

  - name: Setup utilities in cache
    tags: ['cache']
    set_fact:
      cacheable: yes
      qpid_stat: '{{ apigee_home }}/apigee-qpidd/bin/qpid-stat'
      check_queue_depth: '{{ apigee_home }}/apigee-qpidd/bin/check_queue_depth.py'

  when: profile is defined and profile == 'qs'
