---
- name: Checking for Management Server Port
  register: ms_port_status
  ignore_errors: true
  wait_for:
    port: "{{ ms_port | default ('8080') }}"
    host: "{{ private_address | default(ansible_default_ipv4.address) }}"
    timeout: 1

- name: Management Server Port Status report
  debug:
    var: ms_port_status

- name: Management server is not running
  fail:
    msg: "Management server is not running"
  when: ms_port_status | failed

- name: Apigee provision installation with proxy
  shell: '/opt/apigee/apigee-service/bin/apigee-service apigee-provision install'
  environment:
    no_proxy: "{{ no_proxy | default('') }}"
    http_proxy: "{{ http_proxy | default('') }}"
    https_proxy: "{{ https_proxy | default('') }}"

- name: Iterate over Orgs and Envs
  include_tasks: setup-org.yml
  with_items: "{{ tenants }}"
  loop_control:
    loop_var: tenant
