---
# defaults file for apigee-opdk-setup-org-config
use_all_mps: y
ms_port: 8080

# Organization name used in Edge
org_name: opdk

# Environment name
env_name: test

# Default for creating a new user in org
new_user: 'y'

# Default for first_name in creating new user
first_name: Opdk

# Default for last_name in creating new user
last_name: User

# Virtual host port for the org
virtual_host_port: 9001

# Virtual Host name for the org
virtual_host_name: default

# Virtual host alias
virtual_host_alias: '127.0.0.1'

# Default analytics group
ax_group: axgroup001

