---
# defaults file for apigee-opdk-setup-silent-file
opdk_monetization: false
opdk_resources_path: /tmp/edge
opdk_license_target_file_path: "{{ opdk_resources_path }}/license.conf"
opdk_smtp_skip: 'y'
opdk_ldap_sid: '1'
opdk_ldap_port: 10389
opdk_enable_ax: 'y'
opdk_mp_pod: 'gateway'
opdk_use_zk_cluster: 'y'
opdk_use_cass_cluster: 'y'
opdk_cass_username: ''
opdk_cass_password: ''
opdk_cass_auth: 'n'
opdk_user_name: 'apigee'
opdk_smtp_mail_from: "apigee"
enable_system_check: 'n'


# Local resource location
local_apigee_path: ~/.apigee

# Local secure resource location
local_apigee_secure_path: ~/.apigee-secure
